export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const SEARCH_PLANETS_START = 'SEARCH_PLANETS_START';
export const SEARCH_PLANETS_SUCCESS = 'SEARCH_PLANETS_SUCCESS';
export const UPDATE_PLANETS = 'UPDATE_PLANETS';
export const RESET_SEARCH_COUNT = 'RESET_SEARCH_COUNT';